pipeline {
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
               // withMaven(maven : 'Maven_Home') {
               withEnv(["JAVA_HOME=jdk_home", "mavenName=Maven_Home"]) {
                    bat 'mvn  clean install'
                    bat 'mvn --version'
                }
            }
        }
    
    
    stage ('Testing Stage') {

            steps {
                withMaven(maven : 'Maven_Home') {
                    bat 'mvn test'
                }
            }
        }
        
         stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven_Home') {
                    bat 'mvn deploy'
                }
            }
        }
   
   }         
}